### PR TITLE
Fixed prompt not getting returned

### PR DESCRIPTION
**Pull request by Lopyter**
Really like the wildcard functionality your script provides.
What annoyed me though, was that the prompt wasn't getting returned, which resulted in prompt information getting lost and not getting saved alongside images in .txt files and/or the png chunk data.

### CODE REVIEW

**Comment by Lopyter** [comment]
Wait never mind. That kind of crashes the processing script after the last image is done. 
I'll have another go at this.

**Comment by Adil3tr** [comment]
I'm not sure how to make a pull request on just the wildcard script, it doesn't seem to be adding it to this list when I make one. 
I'm using batch convert with no output directory, which lets me do img2img to a folder of images. The wildcard script works in the sense that it sees the artist and makes it choose an artist, the issue is that it chooses one artist and uses them for every single generation rather than picking a different one for each individual generation.

**Comment by jtkelm2** [comment]
@Adil3tr Hm, not really sure what batch convert is—is it another user script? If so, this is a more general problem of getting user scripts to play nice with each other... if you do find a solution for this (and if the PR I just accepted didn't spontaneously fix the issue) let me know and I can implement it.

**Comment by Adil3tr** [comment]
> @Adil3tr Hm, not really sure what batch convert is—is it another user script? If so, this is a more general problem of getting user scripts to play nice with each other... if you do find a solution for this (and if the PR I just accepted didn't spontaneously fix the issue) let me know and I can implement it.

So in the img2img tab there's a subtab next to Inpaint called "batch img2img." This allows you to have img2img run on every image in a folder. If I use the wildcard script at the same time, it will choose a value for every wildcard for the first image, and then use that same combination for every image generated, 300 images but only one combination of wildcards. Apparently batch convert also uses the same seed for every image so honestly I may need to ask for a feature added to Automatic itself. Wildcard should be added to it officially, it's my most used function of the whole UI.

**Comment by jtkelm2** [comment]
> Apparently batch convert also uses the same seed for every image so honestly I may need to ask for a feature added to Automatic itself. Wildcard should be added to it officially, it's my most used function of the whole UI.

Yeah, I would like to see this just implemented under the hood in the official repo, but AUTO is (very understandably) conservative when it comes to maintainability and feature creep. On the plus side, wildcards are a pretty simple thing (just text processing), and they add no UI clutter at all. I think the more recent, more complicated, more niche feature of prompt-swapping being added officially is a decent precedent for including wildcards, too.

**Pull request closed without merging**
